In [1]:
import pandas as pd
import numpy as np


In [2]:

data=pd.read_csv("weatherHistory.csv")
data


Formatted Date        Summary Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain   
5      2006-04-01 05:00:00.000 +0200  Partly Cloudy        rain   
6      2006-04-01 06:00:00.000 +0200  Partly Cloudy        rain   
7      2006-04-01 07:00:00.000 +0200  Partly Cloudy        rain   
8      2006-04-01 08:00:00.000 +0200  Partly Cloudy        rain   
9      2006-04-01 09:00:00.000 +0200  Partly Cloudy        rain   
10     2006-04-01 10:00:00.000 +0200  Partly Cloudy        rain   
11     2006-04-01 11:00:00.000 +0200  Partly Cloudy        rain   
12     2006-04-01 12:00:00.000 +0200  Partly Cloudy        rain   
13     2006-04-01 13:00:00.000 +0200  Partly Cloudy        rain   
14     2006-04-01 14:00:00.000 +0200  Partly Cloudy        rain   
15     2006-04-01 15:00:00.000 +0200  Partly Cloudy        rain   
16     2006-04-01 16:00:00.000 +0200  Partly Cloudy        rain   
17     2006-04-01 17:00:00.000 +0200  Mostly Cloudy        rain   
18     2006-04-01 18:00:00.000 +0200  Mostly Cloudy        rain   
19     2006-04-01 19:00:00.000 +0200  Mostly Cloudy        rain   
20     2006-04-01 20:00:00.000 +0200  Mostly Cloudy        rain   
21     2006-04-01 21:00:00.000 +0200  Mostly Cloudy        rain   
22     2006-04-01 22:00:00.000 +0200  Partly Cloudy        rain   
23     2006-04-01 23:00:00.000 +0200  Mostly Cloudy        rain   
24     2006-04-10 00:00:00.000 +0200  Partly Cloudy        rain   
25     2006-04-10 01:00:00.000 +0200  Partly Cloudy        rain   
26     2006-04-10 02:00:00.000 +0200  Mostly Cloudy        rain   
27     2006-04-10 03:00:00.000 +0200  Partly Cloudy        rain   
28     2006-04-10 04:00:00.000 +0200  Partly Cloudy        rain   
29     2006-04-10 05:00:00.000 +0200  Partly Cloudy        rain   
...                              ...            ...         ...   
96423  2016-09-08 18:00:00.000 +0200  Partly Cloudy        rain   
96424  2016-09-08 19:00:00.000 +0200  Partly Cloudy        rain   
96425  2016-09-08 20:00:00.000 +0200  Partly Cloudy        rain   
96426  2016-09-08 21:00:00.000 +0200  Mostly Cloudy        rain   
96427  2016-09-08 22:00:00.000 +0200  Partly Cloudy        rain   
96428  2016-09-08 23:00:00.000 +0200  Partly Cloudy        rain   
96429  2016-09-09 00:00:00.000 +0200  Partly Cloudy        rain   
96430  2016-09-09 01:00:00.000 +0200          Clear        rain   
96431  2016-09-09 02:00:00.000 +0200          Clear        rain   
96432  2016-09-09 03:00:00.000 +0200          Clear        rain   
96433  2016-09-09 04:00:00.000 +0200          Clear        rain   
96434  2016-09-09 05:00:00.000 +0200          Clear        rain   
96435  2016-09-09 06:00:00.000 +0200          Clear        rain   
96436  2016-09-09 07:00:00.000 +0200          Clear        rain   
96437  2016-09-09 08:00:00.000 +0200  Partly Cloudy        rain   
96438  2016-09-09 09:00:00.000 +0200  Partly Cloudy        rain   
96439  2016-09-09 10:00:00.000 +0200  Partly Cloudy        rain   
96440  2016-09-09 11:00:00.000 +0200  Partly Cloudy        rain   
96441  2016-09-09 12:00:00.000 +0200  Partly Cloudy        rain   
96442  2016-09-09 13:00:00.000 +0200  Partly Cloudy        rain   
96443  2016-09-09 14:00:00.000 +0200  Partly Cloudy        rain   
96444  2016-09-09 15:00:00.000 +0200  Partly Cloudy        rain   
96445  2016-09-09 16:00:00.000 +0200  Partly Cloudy        rain   
96446  2016-09-09 17:00:00.000 +0200  Partly Cloudy        rain   
96447  2016-09-09 18:00:00.000 +0200  Partly Cloudy        rain   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy        rain   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy        rain   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy        rain   
96

In [3]:
from sklearn import preprocessing


In [27]:
label_encoder=preprocessing.LabelEncoder()
data["Summary"]=label_encoder.fit_transform(data["Summary"])
print(data["Summary"])


0        19
1        19
2        17
3        19
4        17
5        19
6        19
7        19
8        19
9        19
10       19
11       19
12       19
13       19
14       19
15       19
16       19
17       17
18       17
19       17
20       17
21       17
22       19
23       17
24       19
25       19
26       17
27       19
28       19
29       19
         ..
96423    19
96424    19
96425    19
96426    17
96427    19
96428    19
96429    19
96430     6
96431     6
96432     6
96433     6
96434     6
96435     6
96436     6
96437    19
96438    19
96439    19
96440    19
96441    19
96442    19
96443    19
96444    19
96445    19
96446    19
96447    19
96448    19
96449    19
96450    19
96451    19
96452    19
Name: Summary, Length: 96453, dtype: int32


In [10]:
dsum_encoded=label_encoder.fit_transform(data["Daily Summary"])
print(dsum_encoded)


[197 197 197 ... 170 170 170]


In [11]:
features=list(zip(sum_encoded,dsum_encoded))
print(features)


[(19, 197), (19, 197), (17, 197), (19, 197), (17, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (19, 197), (17, 197), (17, 197), (17, 197), (17, 197), (17, 197), (19, 197), (17, 197), (19, 111), (19, 111), (17, 111), (19, 111), (19, 111), (19, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (17, 111), (18, 111), (18, 111), (18, 33), (18, 33), (18, 33), (18, 33), (18, 33), (18, 33), (17, 33), (17, 33), (19, 33), (19, 33), (19, 33), (19, 33), (17, 33), (17, 33), (17, 33), (17, 33), (17, 33), (18, 33), (12, 33), (12, 33), (18, 33), (18, 33), (18, 33), (18, 33), (12, 36), (12, 36), (17, 36), (18, 36), (18, 36), (18, 36), (18, 36), (18, 36), (3, 36), (3, 36), (18, 36), (17, 36), (17, 36), (17, 36), (17, 36), (17, 36), (18, 36), (18, 36), (18, 36), (18, 36), (17, 36), (18, 36), (17, 36), (18

In [38]:
data['Temperature (C)'] = data['Temperature (C)'].astype(int)
data['Pressure (millibars)'] = data['Pressure (millibars)'].astype(int)
data['Apparent Temperature (C)'] = data['Apparent Temperature (C)'].astype(int)
data['Humidity'] = data['Humidity'].astype(int)

In [39]:
#generating model

from sklearn.naive_bayes import GaussianNB


In [40]:
#creating Gaussian classifier
model=GaussianNB()


In [41]:
#train the model using training sets
model.fit(features,data['Temperature (C)'])


GaussianNB(priors=None, var_smoothing=1e-09)

In [42]:

#prediction
predicted=model.predict([[0,2]])
print("predicted:", predicted)


predicted: [-2]


In [43]:
x = data.iloc[:, [3, 5]].values  
y = data.iloc[:, -2].values  

In [44]:
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)  
  

In [45]:
# Feature Scaling  
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)  

C:\Users\AGUSTUS DASS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\AGUSTUS DASS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\AGUSTUS DASS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [46]:
    # Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

GaussianNB(priors=None, var_smoothing=1e-09)

In [47]:
    # Predicting the Test set results  
    y_pred = classifier.predict(x_test)  

In [48]:
 y_pred

array([ 987,  987,  986, ..., 1040,  987,  987])

In [49]:
    # Making the Confusion Matrix  
    from sklearn.metrics import confusion_matrix  
    cm = confusion_matrix(y_test, y_pred)  

In [50]:
cm

array([[ 0,  0, 17, ...,  0,  0,  7],
       [ 0,  0,  1, ...,  0,  0,  0],
       [ 0,  0,  1, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=int64)

In [51]:
from sklearn.metrics import classification_report

print("The classification report is as follows...\n")
print(classification_report(y_test, y_pred))

The classification report is as follows...

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       355
         975       0.00      0.00      0.00         1
         976       0.00      0.50      0.00         2
         981       0.00      0.00      0.00         0
         982       0.00      0.00      0.00         1
         985       0.00      0.00      0.00         2
         986       0.00      0.00      0.00         3
         987       0.00      0.80      0.00        10
         988       0.00      0.00      0.00         6
         989       0.00      0.00      0.00         4
         990       0.00      0.00      0.00        11
         991       0.00      0.00      0.00        20
         992       0.00      0.00      0.00        26
         993       0.00      0.00      0.00        24
         994       0.00      0.00      0.00        32
         995       0.00      0.00      0.00        38
         996       0.00      0.00    

C:\Users\AGUSTUS DASS\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\AGUSTUS DASS\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
